services:
  ssa-api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${API_PORT}
      - CLIENT_URL=${APP_URL}
      - AUTH_TOKEN=${APP_TOKEN}
    ports:
      - ${API_PORT}:8080
  ssa-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SOCKET_APP_TOKEN=${APP_TOKEN}
      - REACT_APP_SOCKET_URL=${SOCKET_URL}
    ports:
      - ${APP_PORT}:3000
        